version: '3'
services:
  micronaut-rest:
    build: ./java-micronaut-rest
    ports:
      - "8081:8080"
  spring-rest:
    build: ./java-spring-rest
    ports:
      - "8082:8080"
  go-rest:
    build: ./go-rest
    ports:
      - "8083:8080"